//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string ALLOW {
            get {
                return ResourceManager.GetString("ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string BASIC {
            get {
                return ResourceManager.GetString("BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CUT {
            get {
                return ResourceManager.GetString("CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string EXPIRED {
            get {
                return ResourceManager.GetString("EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FILTER {
            get {
                return ResourceManager.GetString("FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string FOR {
            get {
                return ResourceManager.GetString("FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HIDE {
            get {
                return ResourceManager.GetString("HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MANAGE {
            get {
                return ResourceManager.GetString("MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string OPTIONAL {
            get {
                return ResourceManager.GetString("OPTIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PASTE {
            get {
                return ResourceManager.GetString("PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused.
        /// </summary>
        public static string REFUSED {
            get {
                return ResourceManager.GetString("REFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RESTORE {
            get {
                return ResourceManager.GetString("RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SAVED {
            get {
                return ResourceManager.GetString("SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectOne.
        /// </summary>
        public static string SELECT_ONE {
            get {
                return ResourceManager.GetString("SELECT_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string SHOW {
            get {
                return ResourceManager.GetString("SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved.
        /// </summary>
        public static string UNAPPROVED {
            get {
                return ResourceManager.GetString("UNAPPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        public static string UPDATED_BY {
            get {
                return ResourceManager.GetString("UPDATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        public static string UPDATED_ON {
            get {
                return ResourceManager.GetString("UPDATED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string VISABLE {
            get {
                return ResourceManager.GetString("VISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
