//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Product {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Product() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.Product", typeof(Product).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this product?.
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, product not deleted..
        /// </summary>
        public static string DELETE_ERROR {
            get {
                return ResourceManager.GetString("DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been deleted..
        /// </summary>
        public static string DELETED {
            get {
                return ResourceManager.GetString("DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (CAD).
        /// </summary>
        public static string LABEL_PRICE {
            get {
                return ResourceManager.GetString("LABEL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku#.
        /// </summary>
        public static string LABEL_SKU {
            get {
                return ResourceManager.GetString("LABEL_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string PLURAL {
            get {
                return ResourceManager.GetString("PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, product not saved..
        /// </summary>
        public static string SAVE_ERROR {
            get {
                return ResourceManager.GetString("SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been successfully saved..
        /// </summary>
        public static string SAVED {
            get {
                return ResourceManager.GetString("SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string SINGULAR {
            get {
                return ResourceManager.GetString("SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Product Name.
        /// </summary>
        public static string VALIDATION_NAME {
            get {
                return ResourceManager.GetString("VALIDATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Price.
        /// </summary>
        public static string VALIDATION_PRICE {
            get {
                return ResourceManager.GetString("VALIDATION_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Sku#.
        /// </summary>
        public static string VALIDATION_SKU {
            get {
                return ResourceManager.GetString("VALIDATION_SKU", resourceCulture);
            }
        }
    }
}
