//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmitDemo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitDemo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.SubmitDemo", typeof(SubmitDemo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string LABEL_BODY {
            get {
                return ResourceManager.GetString("LABEL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Modal.
        /// </summary>
        public static string LABEL_CLOSE_MODAL {
            get {
                return ResourceManager.GetString("LABEL_CLOSE_MODAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal Message.
        /// </summary>
        public static string LABEL_MODAL_MESSAGE {
            get {
                return ResourceManager.GetString("LABEL_MODAL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Message.
        /// </summary>
        public static string LABEL_PAGE_MESSAGE {
            get {
                return ResourceManager.GetString("LABEL_PAGE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        public static string LABEL_REDIRECT {
            get {
                return ResourceManager.GetString("LABEL_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Page.
        /// </summary>
        public static string LABEL_RELOAD_PAGE {
            get {
                return ResourceManager.GetString("LABEL_RELOAD_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Container.
        /// </summary>
        public static string LABEL_TARGET_CONTAINER {
            get {
                return ResourceManager.GetString("LABEL_TARGET_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LABEL_TITLE {
            get {
                return ResourceManager.GetString("LABEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Caller.
        /// </summary>
        public static string LABEL_UPDATE_CALLER {
            get {
                return ResourceManager.GetString("LABEL_UPDATE_CALLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, submit demo not processed..
        /// </summary>
        public static string SAVE_ERROR {
            get {
                return ResourceManager.GetString("SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Demo.
        /// </summary>
        public static string SINGULAR {
            get {
                return ResourceManager.GetString("SINGULAR", resourceCulture);
            }
        }
    }
}
